package no.nordicsemi.kotlin.mesh.core.model


/**
 * An enum defining URI Schemes. The values are defined by Bluetooth SIG.
 *
 * Imported from:
 * [Assigned Numbers](https://www.bluetooth.com/specifications/assigned-numbers)
 *  -> 2.7 URI Scheme Name String Mapping
 *
 *  @property rawValue         Raw value of the enum.
 *  @property debugDescription A debug description of the enum.
 */
@Suppress("SpellCheckingInspection")
enum class UriScheme(internal val rawValue: UByte) {
    EMPTY_SCHEME_NAME(rawValue = 0x01u),
    AAA(rawValue = 0x02u),
    AAAS(rawValue = 0x03u),
    ABOUT(rawValue = 0x04u),
    ACAP(rawValue = 0x05u),
    ACCT(rawValue = 0x06u),
    CAP(rawValue = 0x07u),
    CID(rawValue = 0x08u),
    COAP(rawValue = 0x09u),
    COAPS(rawValue = 0x0Au),
    CRID(rawValue = 0x0Bu),
    DATA(rawValue = 0x0Cu),
    DAV(rawValue = 0x0Du),
    DICT(rawValue = 0x0Eu),
    DNS(rawValue = 0x0Fu),
    FILE(rawValue = 0x10u),
    FTP(rawValue = 0x11u),
    GEO(rawValue = 0x12u),
    GO(rawValue = 0x13u),
    GOPHER(rawValue = 0x14u),
    H323(rawValue = 0x15u),
    HTTP(rawValue = 0x16u),
    HTTPS(rawValue = 0x17u),
    IAX(rawValue = 0x18u),
    ICAP(rawValue = 0x19u),
    IM(rawValue = 0x1Au),
    IMAP(rawValue = 0x1Bu),
    INFO(rawValue = 0x1Cu),
    IPP(rawValue = 0x1Du),
    IPPS(rawValue = 0x1Eu),
    IRIS(rawValue = 0x1Fu),
    IRIS_BEEP(rawValue = 0x20u),
    IRIS_XPC(rawValue = 0x21u),
    IRIS_XPCS(rawValue = 0x22u),
    IRIS_LWZ(rawValue = 0x23u),
    JABBER(rawValue = 0x24u),
    LDAP(rawValue = 0x25u),
    MAILTO(rawValue = 0x26u),
    MID(rawValue = 0x27u),
    MSRP(rawValue = 0x28u),
    MSRPS(rawValue = 0x29u),
    MTQP(rawValue = 0x2Au),
    MUPDATE(rawValue = 0x2Bu),
    NEWS(rawValue = 0x2Cu),
    NFS(rawValue = 0x2Du),
    NI(rawValue = 0x2Eu),
    NIH(rawValue = 0x2Fu),
    NNTP(rawValue = 0x30u),
    OPAQUELOCKTOKEN(rawValue = 0x31u),
    POP(rawValue = 0x32u),
    PRES(rawValue = 0x33u),
    RELOAD(rawValue = 0x34u),
    RTSP(rawValue = 0x35u),
    RTSPS(rawValue = 0x36u),
    RTSPU(rawValue = 0x37u),
    SERVICE(rawValue = 0x38u),
    SESSION(rawValue = 0x39u),
    SHTTP(rawValue = 0x3Au),
    SIEVE(rawValue = 0x3Bu),
    SIP(rawValue = 0x3Cu),
    SIPS(rawValue = 0x3Du),
    SMS(rawValue = 0x3Eu),
    SNMP(rawValue = 0x3Fu),
    SOAP_BEEP(rawValue = 0x40u),
    SOAP_BEEPS(rawValue = 0x41u),
    STUN(rawValue = 0x42u),
    STUNS(rawValue = 0x43u),
    TAG(rawValue = 0x44u),
    TEL(rawValue = 0x45u),
    TELNET(rawValue = 0x46u),
    TFTP(rawValue = 0x47u),
    THISMESSAGE(rawValue = 0x48u),
    TN3270(rawValue = 0x49u),
    TIP(rawValue = 0x4Au),
    TURN(rawValue = 0x4Bu),
    TURNS(rawValue = 0x4Cu),
    TV(rawValue = 0x4Du),
    URN(rawValue = 0x4Eu),
    VEMMI(rawValue = 0x4Fu),
    WS(rawValue = 0x50u),
    WSS(rawValue = 0x51u),
    XCON(rawValue = 0x52u),
    XCON_USERID(rawValue = 0x53u),
    XMLRPC_BEEP(rawValue = 0x54u),
    XMLRPC_BEEPS(rawValue = 0x55u),
    XMPP(rawValue = 0x56u),
    Z39_50R(rawValue = 0x57u),
    Z39_50S(rawValue = 0x58u),
    ACR(rawValue = 0x59u),
    ADIUMXTRA(rawValue = 0x5Au),
    AFP(rawValue = 0x5Bu),
    AFS(rawValue = 0x5Cu),
    AIM(rawValue = 0x5Du),
    APT(rawValue = 0x5Eu),
    ATTACHMENT(rawValue = 0x5Fu),
    AW(rawValue = 0x60u),
    BARION(rawValue = 0x61u),
    BESHARE(rawValue = 0x62u),
    BITCOIN(rawValue = 0x63u),
    BOLO(rawValue = 0x64u),
    CALLTO(rawValue = 0x65u),
    CHROME(rawValue = 0x66u),
    CHROME_EXTENSION(rawValue = 0x67u),
    COM_EVENTBRITE_ATTENDEE(rawValue = 0x68u),
    CONTENT(rawValue = 0x69u),
    CVS(rawValue = 0x6Au),
    DLNA_PLAYSINGLE(rawValue = 0x6Bu),
    DLNA_PLAYCONTAINER(rawValue = 0x6Cu),
    DTN(rawValue = 0x6Du),
    DVB(rawValue = 0x6Eu),
    ED2K(rawValue = 0x6Fu),
    FACETIME(rawValue = 0x70u),
    FEED(rawValue = 0x71u),
    FEEDREADY(rawValue = 0x72u),
    FINGER(rawValue = 0x73u),
    FISH(rawValue = 0x74u),
    GG(rawValue = 0x75u),
    GIT(rawValue = 0x76u),
    GIZMOPROJECT(rawValue = 0x77u),
    GTALK(rawValue = 0x78u),
    HAM(rawValue = 0x79u),
    HCP(rawValue = 0x7Au),
    ICON(rawValue = 0x7Bu),
    IPN(rawValue = 0x7Cu),
    IRC(rawValue = 0x7Du),
    IRC6(rawValue = 0x7Eu),
    IRCS(rawValue = 0x7Fu),
    ITMS(rawValue = 0x80u),
    JAR(rawValue = 0x81u),
    JMS(rawValue = 0x82u),
    KEYPARC(rawValue = 0x83u),
    LASTFM(rawValue = 0x84u),
    LDAPS(rawValue = 0x85u),
    MAGNET(rawValue = 0x86u),
    MAPS(rawValue = 0x87u),
    MARKET(rawValue = 0x88u),
    MESSAGE(rawValue = 0x89u),
    MMS(rawValue = 0x8Au),
    MS_HELP(rawValue = 0x8Bu),
    MS_SETTINGS_POWER(rawValue = 0x8Cu),
    MSNIM(rawValue = 0x8Du),
    MUMBLE(rawValue = 0x8Eu),
    MVN(rawValue = 0x8Fu),
    NOTES(rawValue = 0x90u),
    OID(rawValue = 0x91u),
    PALM(rawValue = 0x92u),
    PAPARAZZI(rawValue = 0x93u),
    PKCS11(rawValue = 0x94u),
    PLATFORM(rawValue = 0x95u),
    PROXY(rawValue = 0x96u),
    PSYC(rawValue = 0x97u),
    QUERY(rawValue = 0x98u),
    RES(rawValue = 0x99u),
    RESOURCE(rawValue = 0x9Au),
    RMI(rawValue = 0x9Bu),
    RSYNC(rawValue = 0x9Cu),
    RTMFP(rawValue = 0x9Du),
    RTMP(rawValue = 0x9Eu),
    SECONDLIFE(rawValue = 0x9Fu),
    SFTP(rawValue = 0xA0u),
    SGN(rawValue = 0xA1u),
    SKYPE(rawValue = 0xA2u),
    SMB(rawValue = 0xA3u),
    SMTP(rawValue = 0xA4u),
    SOLDAT(rawValue = 0xA5u),
    SPOTIFY(rawValue = 0xA6u),
    SSH(rawValue = 0xA7u),
    STEAM(rawValue = 0xA8u),
    SUBMIT(rawValue = 0xA9u),
    SVN(rawValue = 0xAAu),
    TEAMSPEAK(rawValue = 0xABu),
    TELIAEID(rawValue = 0xACu),
    THINGS(rawValue = 0xADu),
    UDP(rawValue = 0xAEu),
    UNREAL(rawValue = 0xAFu),
    UT2004(rawValue = 0xB0u),
    VENTRILO(rawValue = 0xB1u),
    VIEW_SOURCE(rawValue = 0xB2u),
    WEBCAL(rawValue = 0xB3u),
    WTAI(rawValue = 0xB4u),
    WYCIWYG(rawValue = 0xB5u),
    XFIRE(rawValue = 0xB6u),
    XRI(rawValue = 0xB7u),
    YMSGR(rawValue = 0xB8u),
    EXAMPLE(rawValue = 0xB9u),
    MS_SETTINGS_CLOUDSTORAGE(rawValue = 0xBAu);

    val debugDescription: String
        get() = when (this) {
            EMPTY_SCHEME_NAME -> "empty scheme name"
            AAA -> "aaa:"
            AAAS -> "aaas:"
            ABOUT -> "about:"
            ACAP -> "acap:"
            ACCT -> "acct:"
            CAP -> "cap:"
            CID -> "cid:"
            COAP -> "coap:"
            COAPS -> "coaps:"
            CRID -> "crid:"
            DATA -> "data:"
            DAV -> "dav:"
            DICT -> "dict:"
            DNS -> "dns:"
            FILE -> "file:"
            FTP -> "ftp:"
            GEO -> "geo:"
            GO -> "go:"
            GOPHER -> "gopher:"
            H323 -> "h323:"
            HTTP -> "http:"
            HTTPS -> "https:"
            IAX -> "iax:"
            ICAP -> "icap:"
            IM -> "im:"
            IMAP -> "imap:"
            INFO -> "info:"
            IPP -> "ipp:"
            IPPS -> "ipps:"
            IRIS -> "iris:"
            IRIS_BEEP -> "iris.beep:"
            IRIS_XPC -> "iris.xpc:"
            IRIS_XPCS -> "iris.xpcs:"
            IRIS_LWZ -> "iris.lwz:"
            JABBER -> "jabber:"
            LDAP -> "ldap:"
            MAILTO -> "mailto:"
            MID -> "mid:"
            MSRP -> "msrp:"
            MSRPS -> "msrps:"
            MTQP -> "mtqp:"
            MUPDATE -> "mupdate:"
            NEWS -> "news:"
            NFS -> "nfs:"
            NI -> "ni:"
            NIH -> "nih:"
            NNTP -> "nntp:"
            OPAQUELOCKTOKEN -> "opaquelocktoken:"
            POP -> "pop:"
            PRES -> "pres:"
            RELOAD -> "reload:"
            RTSP -> "rtsp:"
            RTSPS -> "rtsps:"
            RTSPU -> "rtspu:"
            SERVICE -> "service:"
            SESSION -> "session:"
            SHTTP -> "shttp:"
            SIEVE -> "sieve:"
            SIP -> "sip:"
            SIPS -> "sips:"
            SMS -> "sms:"
            SNMP -> "snmp:"
            SOAP_BEEP -> "soap.beep:"
            SOAP_BEEPS -> "soap.beeps:"
            STUN -> "stun:"
            STUNS -> "stuns:"
            TAG -> "tag:"
            TEL -> "tel:"
            TELNET -> "telnet:"
            TFTP -> "tftp:"
            THISMESSAGE -> "thismessage:"
            TN3270 -> "tn3270:"
            TIP -> "tip:"
            TURN -> "turn:"
            TURNS -> "turns:"
            TV -> "tv:"
            URN -> "urn:"
            VEMMI -> "vemmi:"
            WS -> "ws:"
            WSS -> "wss:"
            XCON -> "xcon:"
            XCON_USERID -> "xcon-userid:"
            XMLRPC_BEEP -> "xmlrpc.beep:"
            XMLRPC_BEEPS -> "xmlrpc.beeps:"
            XMPP -> "xmpp:"
            Z39_50R -> "z39.50r:"
            Z39_50S -> "z39.50s:"
            ACR -> "acr:"
            ADIUMXTRA -> "adiumxtra:"
            AFP -> "afp:"
            AFS -> "afs:"
            AIM -> "aim:"
            APT -> "apt:"
            ATTACHMENT -> "attachment:"
            AW -> "aw:"
            BARION -> "barion:"
            BESHARE -> "beshare:"
            BITCOIN -> "bitcoin:"
            BOLO -> "bolo:"
            CALLTO -> "callto:"
            CHROME -> "chrome:"
            CHROME_EXTENSION -> "chrome-extension:"
            COM_EVENTBRITE_ATTENDEE -> "com-eventbrite-attendee:"
            CONTENT -> "content:"
            CVS -> "cvs:"
            DLNA_PLAYSINGLE -> "dlna-playsingle:"
            DLNA_PLAYCONTAINER -> "dlna-playcontainer:"
            DTN -> "dtn:"
            DVB -> "dvb:"
            ED2K -> "ed2k:"
            FACETIME -> "facetime:"
            FEED -> "feed:"
            FEEDREADY -> "feedready:"
            FINGER -> "finger:"
            FISH -> "fish:"
            GG -> "gg:"
            GIT -> "git:"
            GIZMOPROJECT -> "gizmoproject:"
            GTALK -> "gtalk:"
            HAM -> "ham:"
            HCP -> "hcp:"
            ICON -> "icon:"
            IPN -> "ipn:"
            IRC -> "irc:"
            IRC6 -> "irc6:"
            IRCS -> "ircs:"
            ITMS -> "itms:"
            JAR -> "jar:"
            JMS -> "jms:"
            KEYPARC -> "keyparc:"
            LASTFM -> "lastfm:"
            LDAPS -> "ldaps:"
            MAGNET -> "magnet:"
            MAPS -> "maps:"
            MARKET -> "market:"
            MESSAGE -> "message:"
            MMS -> "mms:"
            MS_HELP -> "ms-help:"
            MS_SETTINGS_POWER -> "ms-settings-power:"
            MSNIM -> "msnim:"
            MUMBLE -> "mumble:"
            MVN -> "mvn:"
            NOTES -> "notes:"
            OID -> "oid:"
            PALM -> "palm:"
            PAPARAZZI -> "paparazzi:"
            PKCS11 -> "pkcs11:"
            PLATFORM -> "platform:"
            PROXY -> "proxy:"
            PSYC -> "psyc:"
            QUERY -> "query:"
            RES -> "res:"
            RESOURCE -> "resource:"
            RMI -> "rmi:"
            RSYNC -> "rsync:"
            RTMFP -> "rtmfp:"
            RTMP -> "rtmp:"
            SECONDLIFE -> "secondlife:"
            SFTP -> "sftp:"
            SGN -> "sgn:"
            SKYPE -> "skype:"
            SMB -> "smb:"
            SMTP -> "smtp:"
            SOLDAT -> "soldat:"
            SPOTIFY -> "spotify:"
            SSH -> "ssh:"
            STEAM -> "steam:"
            SUBMIT -> "submit:"
            SVN -> "svn:"
            TEAMSPEAK -> "teamspeak:"
            TELIAEID -> "teliaeid:"
            THINGS -> "things:"
            UDP -> "udp:"
            UNREAL -> "unreal:"
            UT2004 -> "ut2004:"
            VENTRILO -> "ventrilo:"
            VIEW_SOURCE -> "view-source:"
            WEBCAL -> "webcal:"
            WTAI -> "wtai:"
            WYCIWYG -> "wyciwyg:"
            XFIRE -> "xfire:"
            XRI -> "xri:"
            YMSGR -> "ymsgr:"
            EXAMPLE -> "example:"
            MS_SETTINGS_CLOUDSTORAGE -> "ms-settings-cloudstorage:"
        }

    internal companion object {

        /**
         * Creates a [UriScheme] for a [rawValue], or `null` if no such enum exists.
         *
         * @param rawValue Raw value of the enum.
         * @return corresponding [UriScheme] or null otherwise.
         */
        fun from(rawValue: UByte) = entries.firstOrNull { it.rawValue == rawValue }
    }
}